f<-1:2880
png(filename = "plot3.png", width = 480, height = 480, units = "px")
par(mfrow=c(1,1))
plot(f,as.numeric(as.character(data_set$Sub_metering_1)), type="n", xaxt="n",ylab="Energy sub metering",xlab="")
axis(1,at=c(1,1441,2881),labels=c("Thu","Fri","Sat"))
lines(f,as.numeric(as.character(data_set$Sub_metering_1)))
lines(f,as.numeric(as.character(data_set$Sub_metering_2)),col="red")
lines(f,as.numeric(as.character(data_set$Sub_metering_3)),col="blue")
legend("topright", lty=c(1,1), col = c("black", "blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()